url: https://longly.info
content_separator: "<!-- separator -->"

collections_dir: colllections
collections:
    authors:
        output: true
    resumes:
        output: false
    apps:
        output: true
        permalink: /:name

defaults:
    - scope:
          path: "" # an empty string here means all files in the project
          type: "authors"
      values:
          layout: "author"
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"
    - scope:
          path: ""
      values:
          layout: "default"

plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    math_engine: mathjax
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        default_lang: html
