url: https://qatips.dev

content_separator: "<!-- separator -->"

sass:
    sass_dir: assets/css
    style: compressed

collections_dir: colllections
collections:
    authors:
        output: true
    resumes:
        output: false
    apps:
        output: true
        permalink: /:name

defaults:
    - scope:
          path: ""
          type: "authors"
      values:
          layout: "author"
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"
    - scope:
          path: ""
      values:
          layout: "default"

plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag

markdown: kramdown
syntax_highlighter: rouge
kramdown:
    input: GFM
    syntax_highlighter_opts:
        default_lang: html
